#!/usr/bin/env bash -e
# Simple wrapper around the hash_password utility inside of our webapp to ensure that
# the logic is identical. Use this to manually update the password_hash value in config/users.yml
#
# Usage: hash_password mypassword

cd $(dirname $0)/..

source venv/bin/activate

python -c "from webserver.utils.passwords import hash_password; print(hash_password('$1'))"
