#!/usr/bin/env bash

cd $(dirname $0)/..

if [[ -d venv ]]; then
    >&2 echo "Removing venv directory"
    rm -rf venv
fi

# This is the python we're using
python3.6 -m venv venv

source venv/bin/activate
pip install -r requirements.txt
